import eslintComments from "@eslint-community/eslint-plugin-eslint-comments"
import js from "@eslint/js"
import json from "@eslint/json"
import prettierConfig from "eslint-config-prettier"
import jsdoc from "eslint-plugin-jsdoc"
import noUnsanitized from "eslint-plugin-no-unsanitized"
import packageJson, { configs as packageJsonConfigs } from "eslint-plugin-package-json"
import promise from "eslint-plugin-promise"
import regexp from "eslint-plugin-regexp"
import security from "eslint-plugin-security"
import sonarjs from "eslint-plugin-sonarjs"
import tsdoc from "eslint-plugin-tsdoc"
import unicorn from "eslint-plugin-unicorn"
import { defineConfig } from "eslint/config"
import globals from "globals"
import tseslint from "typescript-eslint"

const commonRules = {
        curly: ["warn", "multi"],
        eqeqeq: ["warn", "smart"],
        "no-console": ["warn", { allow: ["warn", "error"] }],
        "no-constant-condition": ["warn", { checkLoops: false }],
        "one-var": ["warn", { const: "consecutive", let: "consecutive" }],
        "prefer-destructuring": ["warn", { object: true, array: true }],
    },
    offGeral = Object.fromEntries(
        [
            "class-methods-use-this",
            "complexity",
            "func-names",
            "func-style",
            "id-length",
            "id-match",
            "init-declarations",
            "max-depth",
            "max-lines",
            "max-lines-per-function",
            "max-nested-callbacks",
            "max-params",
            "max-statements",
            "no-alert",
            "no-bitwise",
            "no-confusing-arrow",
            "no-continue",
            "no-eq-null",
            "no-inline-comments",
            "no-magic-numbers",
            "no-nested-ternary",
            "no-param-reassign",
            "no-plusplus",
            "no-ternary",
            "no-throw-literal",
            "no-undefined",
            "no-underscore-dangle",
            "no-warning-comments",
            "sort-imports",
            "sort-keys",
            "sort-vars",
            "@typescript-eslint/max-params",
            "@typescript-eslint/naming-convention",
            "@typescript-eslint/no-confusing-void-expression",
            "@typescript-eslint/no-extraneous-class",
            "@typescript-eslint/no-magic-numbers",
            "@typescript-eslint/no-non-null-assertion",
            "@typescript-eslint/no-unsafe-return",
            "@typescript-eslint/no-unsafe-type-assertion",
            "@typescript-eslint/only-throw-error",
            "@typescript-eslint/prefer-readonly-parameter-types",
            "jsdoc/check-examples",
            "jsdoc/check-param-names",
            "jsdoc/check-values",
            "jsdoc/lines-before-block",
            "jsdoc/match-name",
            "jsdoc/no-missing-syntax",
            "jsdoc/no-restricted-syntax",
            "jsdoc/no-undefined-types",
            "jsdoc/require-example",
            "jsdoc/require-file-overview",
            "jsdoc/require-jsdoc",
            "jsdoc/require-param",
            "jsdoc/require-param-type",
            "jsdoc/require-returns",
            "jsdoc/require-returns-type",
            "jsdoc/require-tags",
            "jsdoc/text-escaping",
            "regexp/letter-case",
            "security/detect-non-literal-fs-filename",
            "security/detect-object-injection",
            "security/detect-possible-timing-attacks",
            "sonarjs/assertions-in-test-cases",
            "sonarjs/assertions-in-tests",
            "sonarjs/async-test-assertions",
            "sonarjs/aws-apigateway-public-api",
            "sonarjs/aws-ec2-rds-dms-public",
            "sonarjs/aws-ec2-unencrypted-ebs-volume",
            "sonarjs/aws-efs-unencrypted",
            "sonarjs/aws-iam-all-privileges",
            "sonarjs/aws-iam-privilege-escalation",
            "sonarjs/aws-iam-public-access",
            "sonarjs/aws-opensearchservice-domain",
            "sonarjs/aws-rds-unencrypted-databases",
            "sonarjs/aws-restricted-ip-admin-access",
            "sonarjs/aws-s3-bucket-granted-access",
            "sonarjs/aws-s3-bucket-insecure-http",
            "sonarjs/aws-s3-bucket-public-access",
            "sonarjs/aws-s3-bucket-versioning",
            "sonarjs/aws-sagemaker-unencrypted-notebook",
            "sonarjs/aws-sns-unencrypted-topics",
            "sonarjs/aws-sqs-unencrypted-queue",
            "sonarjs/chai-determinate-assertion",
            "sonarjs/cognitive-complexity",
            "sonarjs/content-length",
            "sonarjs/content-security-policy",
            "sonarjs/cookie-no-httponly",
            "sonarjs/cors",
            "sonarjs/csrf",
            "sonarjs/cyclomatic-complexity",
            "sonarjs/disabled-resource-integrity",
            "sonarjs/disabled-timeout",
            "sonarjs/dompurify-unsafe-config",
            "sonarjs/dynamically-constructed-templates",
            "sonarjs/elseif-without-else",
            "sonarjs/encryption-secure-mode",
            "sonarjs/explicit-test-skip",
            "sonarjs/expression-complexity",
            "sonarjs/file-header",
            "sonarjs/file-permissions",
            "sonarjs/file-uploads",
            "sonarjs/hardcoded-secret-signatures",
            "sonarjs/hashing",
            "sonarjs/hooks-before-test-cases",
            "sonarjs/insecure-cookie",
            "sonarjs/insecure-jwt-token",
            "sonarjs/inverted-assertion-arguments",
            "sonarjs/jsx-no-leaked-render",
            "sonarjs/link-with-target-blank",
            "sonarjs/max-lines-per-function",
            "sonarjs/no-angular-bypass-sanitization",
            "sonarjs/no-clear-text-protocols",
            "sonarjs/no-code-after-done",
            "sonarjs/no-dead-store",
            "sonarjs/no-debounce-throttle-in-render",
            "sonarjs/no-debug-commands-in-ui-tests",
            "sonarjs/no-default-utility-imports",
            "sonarjs/no-duplicate-parameterized-test-case",
            "sonarjs/no-duplicate-string",
            "sonarjs/no-duplicate-test-title",
            "sonarjs/no-empty-parameterized-test-dataset",
            "sonarjs/no-empty-test-file",
            "sonarjs/no-empty-test-title",
            "sonarjs/no-exclusive-tests",
            "sonarjs/no-fixed-wait-in-tests",
            "sonarjs/no-forced-browser-interaction",
            "sonarjs/no-hardcoded-ip",
            "sonarjs/no-hardcoded-passwords",
            "sonarjs/no-hardcoded-secrets",
            "sonarjs/no-hook-setter-in-body",
            "sonarjs/no-incomplete-assertions",
            "sonarjs/no-interpolation-in-inline-snapshots",
            "sonarjs/no-mime-sniff",
            "sonarjs/no-mutate-reactive-state-in-updated-hook",
            "sonarjs/no-nested-conditional",
            "sonarjs/no-networkidle-wait",
            "sonarjs/no-os-command-from-path",
            "sonarjs/no-redundant-assignments",
            "sonarjs/no-reference-error",
            "sonarjs/no-referrer-policy",
            "sonarjs/no-same-argument-assert",
            "sonarjs/no-session-cookies-on-static-assets",
            "sonarjs/no-skipped-tests",
            "sonarjs/no-table-as-layout",
            "sonarjs/no-trivial-assertions",
            "sonarjs/no-unenclosed-multiline-block",
            "sonarjs/no-uniq-key",
            "sonarjs/no-useless-react-setstate",
            "sonarjs/no-vue-class-component",
            "sonarjs/no-vue-mixins",
            "sonarjs/no-weak-cipher",
            "sonarjs/no-weak-keys",
            "sonarjs/object-alt-content",
            "sonarjs/parameterized-tests",
            "sonarjs/post-message",
            "sonarjs/prefer-cypress-should",
            "sonarjs/prefer-native-axios-alternative",
            "sonarjs/prefer-native-jquery-alternative",
            "sonarjs/prefer-native-lodash-alternative",
            "sonarjs/prefer-specific-assertions",
            "sonarjs/pseudo-random",
            "sonarjs/public-static-readonly",
            "sonarjs/publicly-writable-directories",
            "sonarjs/redundant-type-aliases",
            "sonarjs/review-blockchain-mnemonic",
            "sonarjs/session-regeneration",
            "sonarjs/sql-queries",
            "sonarjs/stable-tests",
            "sonarjs/strict-transport-security",
            "sonarjs/synchronous-exception-assertions",
            "sonarjs/synchronous-suite-callback",
            "sonarjs/table-header",
            "sonarjs/table-header-reference",
            "sonarjs/test-check-exception",
            "sonarjs/testing-library-prefer-query-by-disappearance",
            "sonarjs/testing-library-query-assertion",
            "sonarjs/todo-tag",
            "sonarjs/unverified-certificate",
            "sonarjs/unverified-hostname",
            "sonarjs/vitest-mock-at-module-scope",
            "sonarjs/weak-ssl",
            "sonarjs/x-powered-by",
            "sonarjs/xml-parser-xxe",
            "unicorn/catch-error-name",
            "unicorn/consistent-arrow-return-style",
            "unicorn/consistent-boolean-name",
            "unicorn/consistent-class-member-order",
            "unicorn/max-nested-calls",
            "unicorn/name-replacements",
            "unicorn/no-array-callback-reference",
            "unicorn/no-array-reduce",
            "unicorn/no-asterisk-prefix-in-documentation-comments",
            "unicorn/no-nested-ternary",
            "unicorn/no-null",
            "unicorn/no-unreadable-array-destructuring",
            "unicorn/prevent-abbreviations",
            "@typescript-eslint/no-deprecated",
            "@typescript-eslint/switch-exhaustiveness-check",
            "@typescript-eslint/no-unsafe-assignment",
            "@typescript-eslint/no-unsafe-argument",
            "@typescript-eslint/no-unsafe-call",
            "@typescript-eslint/strict-boolean-expressions",
            "unicorn/new-for-builtins",
            "unicorn/switch-case-braces",
            "@typescript-eslint/member-ordering",
        ].map(ruleName => [ruleName, "off"])
    )

export default defineConfig([
    { linterOptions: { reportUnusedDisableDirectives: "warn" }, ignores: ["**/node_modules/**", "pessoal/**"] },
    { ignores: ["./package.json", "./package-lock.json", "**/schemas/**"], files: ["**/*.json"], language: "json/json", extends: [json.configs.recommended] },
    { ignores: ["./package.json", "./package-lock.json", "**/schemas/**"], files: ["**/*.jsonc"], language: "json/jsonc", extends: [json.configs.recommended] },
    { ignores: ["./package.json", "./package-lock.json", "**/schemas/**"], files: ["**/*.json5"], language: "json/json5", extends: [json.configs.recommended] },
    { files: ["./package.json"], plugins: { "package-json": packageJson }, extends: [packageJsonConfigs.recommended] },

    {
        files: ["**/*.{ts,tsx,mts,cts}"],
        extends: [js.configs.all, tseslint.configs.all, unicorn.configs.all, jsdoc.configs["flat/recommended-typescript"], regexp.configs.all, promise.configs["flat/recommended"], security.configs.recommended],
        plugins: { "no-unsanitized": noUnsanitized, "@eslint-community/eslint-comments": eslintComments, regexp, sonarjs, tsdoc, unicorn, promise, security },
        languageOptions: { ecmaVersion: "latest", sourceType: "module", globals: { ...globals.browser, ...globals.node, ...globals.es2027 }, parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname } },
        rules: {
            ...commonRules,
            ...offGeral,
            "@typescript-eslint/no-unused-expressions": ["warn", { allowTernary: true }],
            "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
            "@typescript-eslint/no-use-before-define": ["warn", { functions: false, classes: true, variables: true }],
        },
    },

    prettierConfig,
])
