import eslintComments from "@eslint-community/eslint-plugin-eslint-comments"
import js from "@eslint/js"
import json from "@eslint/json"
import markdown from "@eslint/markdown"
import importX from "eslint-plugin-import-x"
import jsdoc from "eslint-plugin-jsdoc"
import n from "eslint-plugin-n"
import noUnsanitized from "eslint-plugin-no-unsanitized"
import packageJson, { configs as packageJsonConfigs } from "eslint-plugin-package-json"
import promise from "eslint-plugin-promise"
import regexp from "eslint-plugin-regexp"
import security from "eslint-plugin-security"
import sonarjs from "eslint-plugin-sonarjs"
import tsdoc from "eslint-plugin-tsdoc"
import unicorn from "eslint-plugin-unicorn"
import { defineConfig } from "eslint/config"
import globals from "globals"
import tseslint from "typescript-eslint"

const allPluginRules = Object.fromEntries(
        Object.entries({ jsdoc, sonarjs, tsdoc, unicorn }).flatMap(([pluginName, plugin]) =>
            Object.entries(plugin.rules ?? {})
                .filter(([, rule]) => !rule.meta?.languages || rule.meta.languages.includes("js/js"))
                .map(([ruleName]) => [`${pluginName}/${ruleName}`, "warn"])
        )
    ),
    allJsonRules = Object.fromEntries(Object.keys(json.rules).map(ruleName => [`json/${ruleName}`, "warn"])),
    allMarkdownRules = Object.fromEntries(
        Object.keys(markdown.rules).map(ruleName => [`markdown/${ruleName}`, "warn"])
    ),
    allAdditionalPluginRules = Object.fromEntries(
        Object.entries({
            "no-unsanitized": noUnsanitized,
            "@eslint-community/eslint-comments": eslintComments,
            regexp,
            promise,
            security,
        }).flatMap(([pluginName, plugin]) =>
            Object.keys(plugin.rules ?? {}).map(ruleName => [`${pluginName}/${ruleName}`, "warn"])
        )
    ),
    commonConfig = {
        eqeqeq: ["off", "smart"],
        curly: ["warn", "multi"],
        "no-console": ["warn", { allow: ["warn", "error"] }],
        "no-constant-condition": ["warn", { checkLoops: false }],
        "no-unused-expressions": ["warn", { allowTernary: true }],
        "one-var": ["warn", { const: "consecutive", let: "consecutive" }],
        "prefer-destructuring": ["warn", { object: true, array: false }],
    },
    offGeral = Object.fromEntries(
        [
            "no-confusing-arrow",
            "no-nested-ternary",
            "no-param-reassign",
            "security/detect-object-injection",
            "security/detect-non-literal-fs-filename",
            "sonarjs/assertions-in-test-cases",
            "sonarjs/assertions-in-tests",
            "sonarjs/async-test-assertions",
            "sonarjs/aws-apigateway-public-api",
            "sonarjs/aws-ec2-rds-dms-public",
            "sonarjs/aws-ec2-unencrypted-ebs-volume",
            "sonarjs/aws-efs-unencrypted",
            "sonarjs/aws-iam-all-privileges",
            "sonarjs/aws-iam-privilege-escalation",
            "sonarjs/aws-iam-public-access",
            "sonarjs/aws-opensearchservice-domain",
            "sonarjs/aws-rds-unencrypted-databases",
            "sonarjs/aws-restricted-ip-admin-access",
            "sonarjs/aws-s3-bucket-granted-access",
            "sonarjs/aws-s3-bucket-insecure-http",
            "sonarjs/aws-s3-bucket-public-access",
            "sonarjs/aws-s3-bucket-versioning",
            "sonarjs/aws-sagemaker-unencrypted-notebook",
            "sonarjs/aws-sns-unencrypted-topics",
            "sonarjs/aws-sqs-unencrypted-queue",
            "sonarjs/chai-determinate-assertion",
            "sonarjs/cognitive-complexity",
            "sonarjs/content-length",
            "sonarjs/content-security-policy",
            "sonarjs/cookie-no-httponly",
            "sonarjs/cors",
            "sonarjs/csrf",
            "sonarjs/cyclomatic-complexity",
            "sonarjs/disabled-resource-integrity",
            "sonarjs/disabled-timeout",
            "sonarjs/dompurify-unsafe-config",
            "sonarjs/dynamically-constructed-templates",
            "sonarjs/elseif-without-else",
            "sonarjs/encryption-secure-mode",
            "sonarjs/explicit-test-skip",
            "sonarjs/expression-complexity",
            "sonarjs/file-header",
            "sonarjs/file-permissions",
            "sonarjs/file-uploads",
            "sonarjs/hardcoded-secret-signatures",
            "sonarjs/hashing",
            "sonarjs/hooks-before-test-cases",
            "sonarjs/insecure-cookie",
            "sonarjs/insecure-jwt-token",
            "sonarjs/inverted-assertion-arguments",
            "sonarjs/jsx-no-leaked-render",
            "sonarjs/link-with-target-blank",
            "sonarjs/max-lines-per-function",
            "sonarjs/no-angular-bypass-sanitization",
            "sonarjs/no-async-constructor",
            "sonarjs/no-clear-text-protocols",
            "sonarjs/no-code-after-done",
            "sonarjs/no-dead-store",
            "sonarjs/no-debounce-throttle-in-render",
            "sonarjs/no-debug-commands-in-ui-tests",
            "sonarjs/no-default-utility-imports",
            "sonarjs/no-duplicate-parameterized-test-case",
            "sonarjs/no-duplicate-string",
            "sonarjs/no-duplicate-test-title",
            "sonarjs/no-empty-parameterized-test-dataset",
            "sonarjs/no-empty-test-file",
            "sonarjs/no-empty-test-title",
            "sonarjs/no-exclusive-tests",
            "sonarjs/no-fixed-wait-in-tests",
            "sonarjs/no-forced-browser-interaction",
            "sonarjs/no-hardcoded-ip",
            "sonarjs/no-hardcoded-passwords",
            "sonarjs/no-hardcoded-secrets",
            "sonarjs/no-hook-setter-in-body",
            "sonarjs/no-incomplete-assertions",
            "sonarjs/no-interpolation-in-inline-snapshots",
            "sonarjs/no-mime-sniff",
            "sonarjs/no-mutate-reactive-state-in-updated-hook",
            "sonarjs/no-nested-conditional",
            "sonarjs/no-networkidle-wait",
            "sonarjs/no-os-command-from-path",
            "sonarjs/no-redundant-assignments",
            "sonarjs/no-reference-error",
            "sonarjs/no-referrer-policy",
            "sonarjs/no-same-argument-assert",
            "sonarjs/no-session-cookies-on-static-assets",
            "sonarjs/no-skipped-tests",
            "sonarjs/no-table-as-layout",
            "sonarjs/no-trivial-assertions",
            "sonarjs/no-try-promise",
            "sonarjs/no-unenclosed-multiline-block",
            "sonarjs/no-uniq-key",
            "sonarjs/no-useless-react-setstate",
            "sonarjs/no-vue-class-component",
            "sonarjs/no-vue-mixins",
            "sonarjs/no-weak-cipher",
            "sonarjs/no-weak-keys",
            "sonarjs/object-alt-content",
            "sonarjs/parameterized-tests",
            "sonarjs/post-message",
            "sonarjs/prefer-cypress-should",
            "sonarjs/prefer-native-axios-alternative",
            "sonarjs/prefer-native-jquery-alternative",
            "sonarjs/prefer-native-lodash-alternative",
            "sonarjs/prefer-promise-shorthand",
            "sonarjs/prefer-specific-assertions",
            "sonarjs/pseudo-random",
            "sonarjs/public-static-readonly",
            "sonarjs/publicly-writable-directories",
            "sonarjs/redundant-type-aliases",
            "sonarjs/review-blockchain-mnemonic",
            "sonarjs/session-regeneration",
            "sonarjs/sql-queries",
            "sonarjs/stable-tests",
            "sonarjs/strict-transport-security",
            "sonarjs/synchronous-exception-assertions",
            "sonarjs/synchronous-suite-callback",
            "sonarjs/table-header",
            "sonarjs/table-header-reference",
            "sonarjs/test-check-exception",
            "sonarjs/testing-library-prefer-query-by-disappearance",
            "sonarjs/testing-library-query-assertion",
            "sonarjs/todo-tag",
            "sonarjs/unverified-certificate",
            "sonarjs/unverified-hostname",
            "sonarjs/vitest-mock-at-module-scope",
            "sonarjs/weak-ssl",
            "sonarjs/x-powered-by",
            "sonarjs/xml-parser-xxe",
            "sonarjs/too-many-break-or-continue-in-loop",
            "jsdoc/check-examples",
            "jsdoc/check-param-names",
            "jsdoc/check-values",
            "jsdoc/match-name",
            "jsdoc/no-missing-syntax",
            "jsdoc/no-restricted-syntax",
            "jsdoc/no-undefined-types",
            "jsdoc/require-example",
            "jsdoc/require-file-overview",
            "jsdoc/require-jsdoc",
            "jsdoc/require-param",
            "jsdoc/require-returns",
            "jsdoc/require-tags",
            "jsdoc/text-escaping",
            "jsdoc/lines-before-block",
            "tsdoc/syntax",
            "regexp/letter-case",
        ].map(ruleName => [ruleName, "off"])
    ),
    offJS = Object.fromEntries(
        [
            "camelcase",
            "capitalized-comments",
            "class-methods-use-this",
            "complexity",
            "consistent-this",
            "func-names",
            "func-style",
            "id-denylist",
            "id-length",
            "id-match",
            "init-declarations",
            "max-classes-per-file",
            "max-depth",
            "max-lines",
            "max-lines-per-function",
            "max-nested-callbacks",
            "max-params",
            "max-statements",
            "no-alert",
            "no-bitwise",
            "no-continue",
            "no-eq-null",
            "no-inline-comments",
            "no-magic-numbers",
            "no-plusplus",
            "no-ternary",
            "no-throw-literal",
            "no-undefined",
            "no-underscore-dangle",
            "no-useless-assignment",
            "no-warning-comments",
            "sort-imports",
            "sort-keys",
            "sort-vars",
            "strict",
            "vars-on-top",
            "unicorn/catch-error-name",
            "unicorn/consistent-arrow-return-style",
            "unicorn/consistent-boolean-name",
            "unicorn/consistent-class-member-order",
            "unicorn/filename-case",
            "unicorn/max-nested-calls",
            "unicorn/name-replacements",
            "unicorn/no-array-callback-reference",
            "unicorn/no-array-reduce",
            "unicorn/no-asterisk-prefix-in-documentation-comments",
            "unicorn/no-nested-ternary",
            "unicorn/no-null",
            "unicorn/prevent-abbreviations",
            "jsdoc/no-types",
        ].map(ruleName => [ruleName, "off"])
    ),
    offTS = Object.fromEntries(
        [
            "@typescript-eslint/await-thenable",
            "@typescript-eslint/max-params",
            "@typescript-eslint/naming-convention",
            "@typescript-eslint/no-extraneous-class",
            "@typescript-eslint/no-floating-promises",
            "@typescript-eslint/no-magic-numbers",
            "@typescript-eslint/no-misused-promises",
            "@typescript-eslint/no-unsafe-type-assertion",
            "@typescript-eslint/prefer-readonly-parameter-types",
            "jsdoc/require-param-type",
            "jsdoc/require-returns-type",
        ].map(ruleName => [ruleName, "off"])
    ),
    importXCuradoRules = {
        "import-x/no-extraneous-dependencies": "warn",
        "import-x/no-relative-packages": "warn",
        "import-x/newline-after-import": "warn",
        "import-x/first": "warn",
        "import-x/exports-last": "warn",
        "import-x/group-exports": "warn",
    },
    rules = {
        ...commonConfig,
        ...allPluginRules,
        ...allAdditionalPluginRules,
        ...importXCuradoRules,
        ...offGeral,
        ...offJS,
    }

export default defineConfig([
    { linterOptions: { reportUnusedDisableDirectives: "warn" }, ignores: ["**/node_modules/**", "pessoal/**"] },
    {
        ignores: ["./package.json", "./package-lock.json"],
        files: ["**/*.json"],
        language: "json/json",
        extends: [json.configs.recommended],
        rules: allJsonRules,
    },
    {
        ignores: ["./package.json", "./package-lock.json"],
        files: ["**/*.jsonc"],
        language: "json/jsonc",
        extends: [json.configs.recommended],
        rules: allJsonRules,
    },
    {
        ignores: ["./package.json", "./package-lock.json"],
        files: ["**/*.json5"],
        language: "json/json5",
        extends: [json.configs.recommended],
        rules: allJsonRules,
    },
    { files: ["./package.json"], plugins: { "package-json": packageJson }, extends: [packageJsonConfigs.recommended] },
    {
        files: ["**/*.md"],
        extends: [markdown.configs.recommended, markdown.configs.processor],
        rules: allMarkdownRules,
    },
    {
        ignores: [
            "./src/checks.js",
            "./src/config.js",
            "./src/errors.js",
            "./src/i18n.js",
            "./src/math.js",
            "./src/state.js",
            "./src/writing.js",
        ],
        files: ["**/*.{js,mjs,cjs,jsx}"],
        extends: [js.configs.all, unicorn.configs.all],
        plugins: {
            "@eslint-community/eslint-comments": eslintComments,
            "import-x": importX,
            "no-unsanitized": noUnsanitized,
            jsdoc,
            regexp,
            sonarjs,
            tsdoc,
            unicorn,
            promise,
            security,
        },
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
            globals: { ...globals.browser, ...globals.node, ...globals.es2027 },
        },
        rules: {
            ...rules,
            "no-empty-function": "warn",
            "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
            "no-use-before-define": ["warn", { functions: false, classes: true, variables: true }],
            "no-useless-constructor": "warn",
        },
    },
    {
        files: ["**/*.{ts,tsx,mts,cts}"],
        extends: [
            js.configs.all,
            tseslint.configs.all,
            tseslint.configs.strictTypeChecked,
            tseslint.configs.stylisticTypeChecked,
            unicorn.configs.all,
            sonarjs.configs.recommended,
            jsdoc.configs["flat/recommended-typescript"],
        ],
        plugins: {
            "import-x": importX,
            "no-unsanitized": noUnsanitized,
            "@eslint-community/eslint-comments": eslintComments,
            regexp,
            tsdoc,
            unicorn,
            promise,
            security,
        },
        languageOptions: {
            globals: { ...globals.browser, ...globals.node },
            parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
        },
        rules: {
            ...rules,
            ...offTS,
            "@typescript-eslint/consistent-type-imports": "warn",
            "@typescript-eslint/no-confusing-non-null-assertion": "warn",
            "@typescript-eslint/no-dynamic-delete": "warn",
            "@typescript-eslint/no-empty-function": "warn",
            "@typescript-eslint/no-explicit-any": "warn",
            "@typescript-eslint/no-import-type-side-effects": "warn",
            "@typescript-eslint/no-inferrable-types": "warn",
            "@typescript-eslint/no-non-null-assertion": "warn",
            "@typescript-eslint/no-shadow": "warn",
            "@typescript-eslint/no-unnecessary-condition": "warn",
            "@typescript-eslint/no-unnecessary-type-assertion": "warn",
            "@typescript-eslint/no-unnecessary-type-conversion": "warn",
            "@typescript-eslint/no-unused-expressions": ["warn", { allowTernary: true }],
            "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
            "@typescript-eslint/no-use-before-define": ["warn", { functions: false, classes: true, variables: true }],
            "@typescript-eslint/no-useless-constructor": "warn",
            "@typescript-eslint/only-throw-error": "warn",
            "@typescript-eslint/prefer-for-of": "warn",
            "@typescript-eslint/prefer-nullish-coalescing": "warn",
            "@typescript-eslint/prefer-optional-chain": "warn",
            "@typescript-eslint/prefer-readonly": "warn",
            "@typescript-eslint/restrict-plus-operands": "warn",
            "@typescript-eslint/switch-exhaustiveness-check": "warn",
        },
    },
    {
        files: ["./bump-version.js", "**/*.config.{js,mjs,cjs}"],
        plugins: { n },
        extends: [n.configs["flat/recommended"]],
        rules: { "n/no-extraneous-import": "off" },
    },
    {
        files: ["./eslint.config.js"],
        rules: {
            "import-x/max-dependencies": "off",
            "import-x/no-default-export": "off",
            "import-x/no-named-as-default": "off",
            "import-x/no-rename-default": "off",
            "n/no-missing-import": "off",
            "import-x/no-extraneous-dependencies": "off",
            "n/no-unpublished-import": "off",
            "import-x/no-relative-packages": "off",
        },
    },
])
