import js from "@eslint/js"
import json from "@eslint/json"
import prettierConfig from "eslint-config-prettier"
import jsdoc from "eslint-plugin-jsdoc"
import { defineConfig } from "eslint/config"
import globals from "globals"
import tseslint from "typescript-eslint"

export default defineConfig([
    { linterOptions: { reportUnusedDisableDirectives: "warn" } },
    { ignores: ["**/node_modules/**", "package-lock.json"] },

    // === JAVASCRIPT ===
    {
        files: ["**/*.{js,mjs,cjs,jsx}"],
        plugins: { js, jsdoc },
        extends: ["js/recommended", "jsdoc/flat/recommended"],
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
            globals: { ...globals.browser, ...globals.node, ...globals.es2027 },
        },
        rules: {
            "no-constant-condition": ["error", { checkLoops: false }],
            "no-console": ["warn", { allow: ["warn", "error"] }],
            "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
            "consistent-return": "warn",
            "no-throw-literal": "error",
            "prefer-const": ["warn", { destructuring: "all" }],
            "no-var": "error",
            "no-shadow": "warn",
            "block-scoped-var": "error",
            "no-undef-init": "warn",
            eqeqeq: ["off", "smart"],
            yoda: "warn",
            curly: ["warn", "multi-line"],
            "no-else-return": ["warn", { allowElseIf: false }],
            "no-lonely-if": "warn",
            "no-unneeded-ternary": "warn",
            "default-case": "warn",
            "default-case-last": "warn",
            "prefer-arrow-callback": "warn",
            "arrow-body-style": ["warn", "as-needed"],
            "require-await": "warn",
            "object-shorthand": ["warn", "always"],
            "prefer-template": "warn",
            "prefer-spread": "warn",
            "prefer-rest-params": "warn",
            "no-array-constructor": "warn",
            "no-new-object": "warn",
            "no-useless-concat": "warn",
            "no-useless-computed-key": "warn",
            "no-useless-rename": "warn",
            "no-multi-assign": "warn",
            "no-implicit-coercion": "warn",
            complexity: ["warn", 30],
            "max-depth": ["warn", 4],

            "no-await-in-loop": "warn",
            "no-promise-executor-return": "error",
            "require-atomic-updates": "warn",
            "no-negated-condition": "warn",
            "prefer-exponentiation-operator": "warn",
            "prefer-regex-literals": "warn",
            "no-unreachable-loop": "error",
            radix: "warn",
            "no-useless-return": "warn",
            "guard-for-in": "warn",
            "no-lone-blocks": "warn",
            "no-extra-bind": "warn",
            "prefer-object-spread": "warn",
            "no-unused-expressions": ["warn", { allowTernary: true }],
            "no-new-func": "warn",
            "prefer-object-has-own": "warn",
            "no-useless-call": "warn",
            "prefer-named-capture-group": "warn",
            "max-params": ["warn", 8],

            "jsdoc/check-alignment": "warn",
            "jsdoc/check-param-names": "warn",
            "jsdoc/check-property-names": "warn",
            "jsdoc/check-tag-names": "warn",
            "jsdoc/check-types": "warn",
            "jsdoc/check-values": "warn",
            "jsdoc/no-undefined-types": "off",
            "jsdoc/require-jsdoc": "off",
            "jsdoc/require-param": "off",
            "jsdoc/require-param-description": "off",
            "jsdoc/require-param-name": "warn",
            "jsdoc/require-returns": "off",
            "jsdoc/require-returns-description": "off",
            "jsdoc/require-property-name": "warn",
            "jsdoc/require-returns-check": "warn",
            "jsdoc/require-yields-check": "warn",
            "jsdoc/valid-types": "warn",
        },
    },

    // === TYPESCRIPT ===
    ...tseslint.configs.recommended.map(config => ({ ...config, files: ["**/*.{ts,tsx,mts,cts}"] })),
    {
        files: ["**/*.{ts,tsx,mts,cts}"],
        languageOptions: { globals: { ...globals.browser, ...globals.node, ...globals.es2027 } },
        rules: {
            "@typescript-eslint/array-type": ["warn", { default: "array" }],
            "@typescript-eslint/consistent-type-imports": ["warn", { prefer: "type-imports" }],
            "@typescript-eslint/no-empty-function": "warn",
            "@typescript-eslint/no-non-null-assertion": "warn",
            "@typescript-eslint/no-shadow": "warn",
            "@typescript-eslint/no-use-before-define": ["error", { functions: false, classes: true, variables: true }],
            "@typescript-eslint/no-import-type-side-effects": "warn",
            "@typescript-eslint/no-dynamic-delete": "warn",
            "@typescript-eslint/no-confusing-non-null-assertion": "warn",
            "@typescript-eslint/prefer-for-of": "warn",

            "no-console": ["warn", { allow: ["warn", "error"] }],
            "consistent-return": "warn",
            "no-throw-literal": "error",
            "no-shadow": "off",
            "no-use-before-define": "off",
            "prefer-const": ["warn", { destructuring: "all" }],
            "no-var": "error",
            eqeqeq: ["off", "smart"],
            curly: ["warn", "multi-line"],
            "no-else-return": ["warn", { allowElseIf: false }],
            "no-lonely-if": "warn",
            "object-shorthand": ["warn", "always"],
            "prefer-template": "warn",
            "no-duplicate-imports": "error",

            "no-await-in-loop": "warn",
            "no-promise-executor-return": "error",
            "require-atomic-updates": "warn",
            "no-negated-condition": "warn",
            "prefer-exponentiation-operator": "warn",
            "prefer-regex-literals": "warn",
            "no-unreachable-loop": "error",
            radix: "warn",
        },
    },

    // === JSON ===
    { files: ["**/*.json"], plugins: { json }, language: "json/json", extends: ["json/recommended"] },
    { files: ["**/*.jsonc"], plugins: { json }, language: "json/jsonc", extends: ["json/recommended"] },
    { files: ["**/*.json5"], plugins: { json }, language: "json/json5", extends: ["json/recommended"] },

    // === PRETTIER ===
    prettierConfig,
])
